export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_ERROR_DISABLE = "SEARCH_ERROR_DISABLE";

export const SEARCH_ADD_TO_LIST = "SEARCH_ADD_TO_LIST";

export const SEARCH_REMOVE_FROM_LIST = "SEARCH_REMOVE_FROM_LIST";

export const SEARCH_UPDATE_LIST = "SEARCH_UPDATE_LIST";
export const SEARCH_UPDATE_SUCCESS = "SEARCH_UPDATE_SUCCESS";
export const SEARCH_UPDATE_ERROR = "SEARCH_UPDATE_ERROR";

export const SEARCH_UPDATE_CITY_REQUEST = "SEARCH_UPDATE_CITY_REQUEST";
export const SEARCH_UPDATE_CITY_SUCCESS = "SEARCH_UPDATE_CITY_SUCCESS";
export const SEARCH_UPDATE_CITY_ERROR = "SEARCH_UPDATE_CITY_ERROR";

export const SEARCH_UPDATE_ALL_CITY_REQUEST = "SEARCH_UPDATE_ALL_CITY_REQUEST";
export const SEARCH_UPDATE_ALL_CITY_SUCCESS = "SEARCH_UPDATE_ALL_CITY_SUCCESS";
export const SEARCH_UPDATE_ALL_CITY_ERROR = "SEARCH_UPDATE_ALL_CITY_ERROR";
